
language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest .
  - pytest --cov-branch --cov-report term-missing  --cov=code
after_success:
  - bash <(curl -s https://codecov.io/bash)
